import type { ForestAutomation, ForestConnection, ForestSystem } from './forest.types';

export const forestSystems: ForestSystem[] = [
  { id: 'forest', name: 'BonsAI Forest', type: 'CORE', category: 'System Map', status: 'ACTIVE', description: 'Visual layer that shows systems, connections, automation movement and health.', icon: 'root', visualVariant: 'cedar', health: 94, position: { x: 50, y: 44 }, scale: 1.25 },
  { id: 'office', name: 'BonsAI Office', type: 'PRODUCT', category: 'Workspace', status: 'ACTIVE', description: 'Human operational workspace for approvals, daily actions and focused work.', icon: 'office', visualVariant: 'pine', health: 88, position: { x: 22, y: 33 }, scale: .92 },
  { id: 'garden', name: 'BonsAI Garden', type: 'PRODUCT', category: 'Experience', status: 'WAITING', description: 'Separate garden product for visual configuration and crafted customer journeys.', icon: 'garden', visualVariant: 'cherry', health: 72, position: { x: 31, y: 62 }, scale: .82 },
  { id: 'city', name: 'BonsAI City', type: 'PRODUCT', category: 'Company View', status: 'ACTIVE', description: 'High-level company visualization and growth view.', icon: 'city', visualVariant: 'maple', health: 91, position: { x: 72, y: 30 }, scale: .96 },
  { id: 'gmail', name: 'Gmail', type: 'INTEGRATION', category: 'Message Source', status: 'FAILED', description: 'Mock inbound email source. The live integration is not connected in Forest V1.', icon: 'mail', visualVariant: 'willow', health: 43, position: { x: 14, y: 66 }, scale: .72 },
  { id: 'calendar', name: 'Google Calendar', type: 'INTEGRATION', category: 'Schedule Source', status: 'ACTIVE', description: 'Mock calendar signal source for planned work and meetings.', icon: 'calendar', visualVariant: 'juniper', health: 86, position: { x: 80, y: 58 }, scale: .78 },
  { id: 'ygrassil', name: 'Legacy Ygrassil', type: 'AGENT', category: 'Sales Agent', status: 'DISCONNECTED', description: 'Frozen outbound sales agent. Preserved, inspectable, and not used as Forest logic.', icon: 'agent', visualVariant: 'sprout', health: 18, position: { x: 61, y: 62 }, scale: .66 },
];

export const forestConnections: ForestConnection[] = [
  { id: 'calendar-office', sourceSystemId: 'calendar', destinationSystemId: 'office', trigger: 'Calendar event changed', action: 'Create Office work context', status: 'ACTIVE', lastRun: 'Today 13:04', result: 'Meeting context delivered to BonsAI Office.', error: '', nextRun: 'On next event', permissionMode: 'AUTOMATIC', path: 'M 800 348 C 720 295 610 282 500 264 C 390 248 300 210 220 198', marker: { x: 54, y: 42 } },
  { id: 'garden-forest', sourceSystemId: 'garden', destinationSystemId: 'forest', trigger: 'Garden brief updated', action: 'Map product signal into ecosystem state', status: 'WAITING', lastRun: 'Today 09:42', result: 'Brief signal queued for approval.', error: '', nextRun: 'Waiting for Office approval', permissionMode: 'APPROVAL_REQUIRED', path: 'M 310 372 C 360 344 420 304 500 264', marker: { x: 40, y: 52 } },
  { id: 'forest-city', sourceSystemId: 'forest', destinationSystemId: 'city', trigger: 'Forest health recalculated', action: 'Update City growth signal', status: 'ACTIVE', lastRun: 'Today 13:10', result: 'City signal refreshed.', error: '', nextRun: 'Every 30 minutes', permissionMode: 'AUTOMATIC', path: 'M 500 264 C 575 220 640 188 720 180', marker: { x: 62, y: 33 } },
  { id: 'gmail-office', sourceSystemId: 'gmail', destinationSystemId: 'office', trigger: 'Inbox message received', action: 'Prepare human review task', status: 'FAILED', lastRun: 'Today 12:16', result: 'Stopped before task creation.', error: 'Mock mailbox permission missing.', nextRun: 'Retry paused', permissionMode: 'MANUAL', path: 'M 140 396 C 168 324 184 250 220 198', marker: { x: 17, y: 52 } },
  { id: 'ygrassil-forest', sourceSystemId: 'ygrassil', destinationSystemId: 'forest', trigger: 'Outbound signal ready', action: 'Expose agent health only', status: 'DISCONNECTED', lastRun: 'Not running', result: 'Legacy agent preserved outside Forest V1.', error: 'Connection intentionally dormant.', nextRun: 'No schedule', permissionMode: 'MANUAL', path: 'M 610 372 C 574 338 544 300 500 264', marker: { x: 56, y: 50 } },
  { id: 'office-forest', sourceSystemId: 'office', destinationSystemId: 'forest', trigger: 'Office approval granted', action: 'Release approved automation signal', status: 'WAITING', lastRun: 'Today 10:22', result: 'Awaiting approval.', error: '', nextRun: 'When approved', permissionMode: 'APPROVAL_REQUIRED', path: 'M 220 198 C 300 228 404 252 500 264', marker: { x: 35, y: 38 } },
];

export const forestAutomations: ForestAutomation[] = [
  { id: 'morning-context', name: 'Morning Context Flow', description: 'Calendar signal becomes an Office work context.', trigger: 'First calendar update after 08:00', steps: ['Read mock calendar event', 'Route through BonsAI Forest', 'Create Office context'], status: 'ACTIVE', permissionMode: 'AUTOMATIC', lastRun: 'Today 13:04', nextRun: 'Tomorrow 08:05', successCount: 42, failureCount: 1, connectionIds: ['calendar-office'] },
  { id: 'garden-growth', name: 'Garden to City Signal', description: 'Garden product signal updates the high-level City view through Forest.', trigger: 'Garden brief reaches review', steps: ['Receive Garden signal', 'Wait for Office approval', 'Update City growth map'], status: 'WAITING', permissionMode: 'APPROVAL_REQUIRED', lastRun: 'Today 09:42', nextRun: 'After approval', successCount: 12, failureCount: 0, connectionIds: ['garden-forest', 'forest-city'] },
  { id: 'reply-routing', name: 'Reply Routing', description: 'Inbound message should become a human task, but the mock source is failed.', trigger: 'New inbound message', steps: ['Receive Gmail signal', 'Validate mailbox permission', 'Create Office task'], status: 'FAILED', permissionMode: 'MANUAL', lastRun: 'Today 12:16', nextRun: 'Paused', successCount: 18, failureCount: 3, connectionIds: ['gmail-office'] },
  { id: 'legacy-watch', name: 'Legacy Agent Watch', description: 'Ygrassil is visible as a dormant legacy agent without sending or database access.', trigger: 'Manual inspection only', steps: ['Read mock legacy status', 'Keep outbound dormant', 'Show health in Forest'], status: 'DISCONNECTED', permissionMode: 'MANUAL', lastRun: 'Not running', nextRun: 'No schedule', successCount: 0, failureCount: 0, connectionIds: ['ygrassil-forest'] },
];
