import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Copy,Download,HelpCircle,ImagePlus,Leaf,Menu,RotateCcw,Save,Trash2,Upload,X} from 'lucide-react';
import {BonsaiScene} from './BonsaiScene';
import {businessTypes,features,feelings,fonts,goals,palettes,sections,steps,styles} from './workshopData';
import {loadPictures,removePicture,savePicture} from './storage';
import {Lang,translate} from './i18n';
type Picture={id:string;name:string;url:string};
type DomainStatus='idle'|'checking'|'registered'|'possibly-available'|'invalid'|'error';
type Project={businessName:string;domainName:string;domainStatus:DomainStatus;businessType:string;goal:string;feeling:string[];style:string;palette:string;font:string;sections:string[];features:string[];headline:string;subheadline:string;about:string;cta:string;contact:string;socialLinks:Record<string,string>;pictureIds:string[]};
const blank:Project={businessName:'',domainName:'',domainStatus:'idle',businessType:'',goal:'',feeling:[],style:'',palette:'',font:'',sections:['Hero','Services','About','Contact'],features:[],headline:'',subheadline:'',about:'',cta:'Contact us',contact:'',socialLinks:{},pictureIds:[]},STORE='bonsai-workshop-v2';
const socialPlatforms=['Website','Instagram','Facebook','TikTok','YouTube','LinkedIn','WhatsApp','Google Business','Other link'];
const toggle=(a:string[],v:string)=>a.includes(v)?a.filter(x=>x!==v):[...a,v];
function Brand(){return <div className="brand"><span><Leaf/> BonsAI Garden</span><small>DESIGN • WORKSHOP</small></div>}
function Choice({selected,onClick,children,className=''}:{selected:boolean;onClick:()=>void;children:React.ReactNode;className?:string}){return <button className={`choice ${selected?'selected':''} ${className}`} onClick={onClick}>{children}{selected?<Check className="tick"/>:null}</button>}
export function App(){
 const [started,setStarted]=useState(false),[step,setStep]=useState(0),[project,setProject]=useState<Project>(()=>{try{return {...blank,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return blank}}),[pictures,setPictures]=useState<Picture[]>([]),[help,setHelp]=useState(false),[summary,setSummary]=useState(false),[menu,setMenu]=useState(false),[saved,setSaved]=useState(false),[pulse,setPulse]=useState(0),[lang,setLang]=useState<Lang>(()=>(localStorage.getItem('bonsai-lang') as Lang)||'en');
 const t=(text:string)=>translate(lang,text);
 const palette=palettes.find(x=>x.name===project.palette),tone=palette?.colors?.[1]||'#d5a35d';
 const growth=Math.max(.08,[project.businessName,project.businessType,project.goal,project.feeling.length,project.style,project.palette,project.font,project.sections.length,project.features.length,project.headline,pictures.length].filter(Boolean).length/11);
 useEffect(()=>{loadPictures(project.pictureIds).then(fs=>setPictures(fs.map(({id,file})=>({id,name:file.name,url:URL.createObjectURL(file)}))))},[]);
 useEffect(()=>{document.querySelector('.work-area')?.scrollTo({top:0})},[step]);
 useEffect(()=>{localStorage.setItem('bonsai-lang',lang);document.documentElement.lang=lang==='ja'?'ja':lang},[lang]);
 const update=<K extends keyof Project>(key:K,value:Project[K])=>{setProject(p=>({...p,[key]:value}));setPulse(Date.now())};
 const persist=()=>{localStorage.setItem(STORE,JSON.stringify(project));setSaved(true);setTimeout(()=>setSaved(false),1500)};
 const next=()=>{persist();setStep(s=>Math.min(9,s+1));setPulse(Date.now())};
 const addPictures=async(e:ChangeEvent<HTMLInputElement>)=>{for(const file of Array.from(e.target.files||[])){const id=crypto.randomUUID();await savePicture(id,file);setPictures(p=>[...p,{id,name:file.name,url:URL.createObjectURL(file)}]);setProject(p=>({...p,pictureIds:[...p.pictureIds,id]}))}e.target.value='';setPulse(Date.now())};
 const delPicture=async(id:string)=>{await removePicture(id);setPictures(p=>p.filter(x=>x.id!==id));setProject(p=>({...p,pictureIds:p.pictureIds.filter(x=>x!==id)}))};
 const reset=()=>{if(!confirm('Start a new concept? Your saved choices will be cleared.'))return;localStorage.removeItem(STORE);project.pictureIds.forEach(removePicture);setProject(blank);setPictures([]);setStep(0)};
 const spec=useMemo(()=>{const socials=Object.entries(project.socialLinks||{}).filter(([,url])=>url.trim()).map(([name,url])=>`${name}: ${url}`).join('\n')||'—';return `BONSAI WEBSITE CONCEPT\n\nBusiness: ${project.businessName||'—'}\nDomain: ${project.domainName||'—'}${project.domainName?` (${project.domainStatus})`:''}\nType: ${project.businessType||'—'}\nGoal: ${project.goal||'—'}\nFeeling: ${project.feeling.join(', ')||'—'}\nStyle: ${project.style||'—'}\nColors: ${project.palette||'—'}\nTypography: ${project.font||'—'}\nSections: ${project.sections.join(', ')}\nFeatures: ${project.features.join(', ')||'—'}\nHeadline: ${project.headline||'—'}\nSubheadline: ${project.subheadline||'—'}\nAbout: ${project.about||'—'}\nCTA: ${project.cta||'—'}\nContact: ${project.contact||'—'}\nSocial links:\n${socials}\nPictures: ${pictures.length}\n\nCreated with BonsAi Studio · itbonsai.pl`},[project,pictures.length]);
 const copy=async()=>{await navigator.clipboard.writeText(spec);setSaved(true);setTimeout(()=>setSaved(false),1500)},download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([spec],{type:'text/plain'}));a.download=`${project.businessName||'bonsai'}-concept.txt`;a.click();URL.revokeObjectURL(a.href)};
 return <main className={`atelier ${started?'workshop':'landing'}`} style={{'--tone':tone,'--c1':palette?.colors?.[0]||'#080909','--c2':tone,'--c3':palette?.colors?.[2]||'#eee6d9'} as React.CSSProperties}><div className="garden-bg"/><div className="vignette"/><div className="scene"><BonsaiScene growth={growth} pulse={pulse}/></div>
 <header><Brand/><div className="lang-switch" aria-label="Language">{(['en','pl','ja'] as Lang[]).map(x=><button key={x} className={lang===x?'active':''} onClick={()=>setLang(x)}>{x==='ja'?'日本語':x.toUpperCase()}</button>)}</div>{started?<div className="top-progress"><b>{String(step+1).padStart(2,'0')}</b> / 10</div>:<nav><button onClick={()=>setStarted(true)}>{t('Workshop')}</button><a href="https://itbonsai.pl" target="_blank" rel="noreferrer">{t('Studio')}</a><button onClick={()=>setHelp(true)}>{t('Help')}</button></nav>}<div className="head-actions">{started?<><button onClick={persist}><Save/> {t(saved?'Saved':'Save progress')}</button><button onClick={()=>setHelp(true)}><HelpCircle/> {t('Help')}</button><button className="outline" onClick={()=>setSummary(true)}>{t('My BonsAI')}</button></>:<button className="outline" onClick={()=>setStarted(true)}>{t('Start workshop')}</button>}<button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button></div></header>
 {!started?<section className="landing-copy"><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>{t('Grow your perfect website.')}</motion.h1><p>{t('Build your website direction step by step. Choose the style, colors, content, features and pictures—then watch your BonsAI grow.')}</p><button className="primary" onClick={()=>setStarted(true)}>{t('Start the workshop')} <ChevronRight/></button><small>{t('Your progress is saved on this device.')}</small></section>:<><aside className="step-rail">{steps.map((name,i)=><button key={name} className={`${i===step?'active':''} ${i<step?'done':''}`} onClick={()=>setStep(i)}><i>{i<step?<Check/>:String(i+1).padStart(2,'0')}</i><span>{t(name)}</span></button>)}</aside><section className="work-area"><AnimatePresence mode="wait"><motion.div key={`${step}-${lang}`} className="step-content" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}><Step lang={lang} step={step} project={project} update={update} pictures={pictures} addPictures={addPictures} delPicture={delPicture} copy={copy} download={download}/></motion.div></AnimatePresence></section><aside className="tree-status"><span>{t('Your website is')} <b>{Math.round(growth*100)}% {t('grown')}</b></span><i><i style={{width:`${growth*100}%`}}/></i><small>{project.style||t('Choose your direction to grow the trunk.')}</small></aside><div className="bottom-nav"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0}><ArrowLeft/> {t('Back')}</button><button className="continue" onClick={step===9?()=>setSummary(true):next}>{step===9?t('Open My BonsAI'):`${lang==='pl'?'Dalej:':lang==='ja'?'次へ:':'Continue to'} ${t(steps[step+1])}`} <ArrowRight/></button></div></>}
 <AnimatePresence>{(help||summary)&&<><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>{setHelp(false);setSummary(false)}}/><motion.aside className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><button className="close" onClick={()=>{setHelp(false);setSummary(false)}} aria-label="Close"><X/></button>{help?<Help lang={lang}/>:<Summary lang={lang} project={project} growth={growth} pictures={pictures} copy={copy} download={download} reset={reset}/>}</motion.aside></>}</AnimatePresence>{menu?<div className="mobile-nav"><button onClick={persist}>{t('Save progress')}</button><button onClick={()=>setHelp(true)}>{t('Help')}</button><button onClick={()=>setSummary(true)}>{t('My BonsAI')}</button></div>:null}</main>
}
type SP={lang:Lang;step:number;project:Project;update:<K extends keyof Project>(k:K,v:Project[K])=>void;pictures:Picture[];addPictures:(e:ChangeEvent<HTMLInputElement>)=>void;delPicture:(id:string)=>void;copy:()=>void;download:()=>void};
function Step({lang,step,project,update,pictures,addPictures,delPicture,copy,download}:SP){const t=(s:string)=>translate(lang,s);const heads=[['Tell us what you are growing.','This gives every later recommendation the right roots.'],['How should people feel?','Choose up to four qualities your website should communicate.'],['Choose the character of your website.','Explore 30 genuinely different design directions.'],['Choose the atmosphere.','The palette immediately changes your living BonsAI.'],['Give your message a voice.','Typography shapes how confident, warm or innovative your brand feels.'],['Build the structure.','Select every section your website needs.'],['Add useful capabilities.','Choose the tools that help customers act.'],['Write the first version.','Add your real message now or refine it with BonsAi Studio later.'],['Bring your brand to life.','Upload logos, team pictures, products, spaces or inspiration.'],['Your BonsAI is ready.','Review the direction and take the specification with you.']][step];return <><span className="kicker">{String(step+1).padStart(2,'0')} / {t(steps[step])}</span><h1>{t(heads[0])}</h1><p className="lead">{t(heads[1])}</p>
 {step===0?<div className="form-stack"><label>{t('Business or project name')}<input value={project.businessName} onChange={e=>update('businessName',e.target.value)} placeholder="e.g. North Shore Architecture"/></label><DomainCheck lang={lang} value={project.domainName} status={project.domainStatus} updateName={v=>update('domainName',v)} updateStatus={v=>update('domainStatus',v)}/><fieldset><legend>{t('Business type')}</legend><div className="option-grid compact">{businessTypes.map(x=><Choice key={x} selected={project.businessType===x} onClick={()=>update('businessType',x)}>{t(x)}</Choice>)}</div></fieldset><fieldset><legend>{t('Main website goal')}</legend><div className="option-grid compact">{goals.map(x=><Choice key={x} selected={project.goal===x} onClick={()=>update('goal',x)}>{t(x)}</Choice>)}</div></fieldset></div>:null}
 {step===1?<div className="option-grid feelings">{feelings.map(x=><Choice key={x} selected={project.feeling.includes(x)} onClick={()=>project.feeling.includes(x)||project.feeling.length<4?update('feeling',toggle(project.feeling,x)):undefined}>{t(x)}<small>{t(project.feeling.includes(x)?'Selected':'Add feeling')}</small></Choice>)}</div>:null}
 {step===2?<div className="option-grid style-options">{styles.map((x,i)=><Choice key={x.id} selected={project.style===x.name} onClick={()=>update('style',x.name)}><span className={`style-art art-${i%8}`}/><b>{x.name}</b><small>{x.description}</small></Choice>)}</div>:null}
 {step===3?<div className="option-grid palette-options">{palettes.map(x=><Choice key={x.id} selected={project.palette===x.name} onClick={()=>update('palette',x.name)}><span className="swatches">{x.colors!.map(c=><i key={c} style={{background:c}}/>)}</span><b>{x.name}</b></Choice>)}</div>:null}
 {step===4?<div className="font-options">{fonts.map((x,i)=><Choice key={x} selected={project.font===x} onClick={()=>update('font',x)} className={`font-${i}`}><span>Aa</span><b>{x}</b><small>Grow ideas into experiences.</small></Choice>)}</div>:null}
 {step===5?<Multi lang={lang} items={sections} selected={project.sections} update={v=>update('sections',v)} type="section"/>:null}{step===6?<Multi lang={lang} items={features} selected={project.features} update={v=>update('features',v)} type="feature"/>:null}
 {step===7?<div className="form-stack"><label>{t('Main headline')}<input value={project.headline} onChange={e=>update('headline',e.target.value)} placeholder="What should customers remember?"/></label><label>{t('Supporting message')}<textarea value={project.subheadline} onChange={e=>update('subheadline',e.target.value)} placeholder="Explain the value in one or two sentences."/></label><label>{t('About your business')}<textarea value={project.about} onChange={e=>update('about',e.target.value)} placeholder="What makes your work different?"/></label><div className="two-fields"><label>{t('Primary button')}<input value={project.cta} onChange={e=>update('cta',e.target.value)}/></label><label>{t('Contact details')}<input value={project.contact} onChange={e=>update('contact',e.target.value)} placeholder="Email, phone or address"/></label></div><fieldset className="social-section"><legend>{t('Social links & online profiles')}</legend><p>{t('Add any links customers should find on your website. Leave the rest empty.')}</p><div className="social-grid">{socialPlatforms.map(name=><label key={name}>{t(name)}<input type="url" inputMode="url" value={project.socialLinks?.[name]||''} onChange={e=>update('socialLinks',{...(project.socialLinks||{}),[name]:e.target.value})} placeholder={name==='WhatsApp'?'https://wa.me/…':name==='Other link'?'https://…':`https://${name.toLowerCase().replace(' ','')}.com/…`} autoCapitalize="none" spellCheck={false}/></label>)}</div></fieldset></div>:null}
 {step===8?<div className="pictures"><label className="upload"><ImagePlus/><b>{t('Add pictures')}</b><span>{t('JPG, PNG or WebP · stored safely on this device')}</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={addPictures}/></label>{pictures.length?<div className="picture-grid">{pictures.map(p=><figure key={p.id}><img src={p.url} alt={p.name}/><figcaption>{p.name}<button onClick={()=>delPicture(p.id)} aria-label={`Remove ${p.name}`}><Trash2/></button></figcaption></figure>)}</div>:<p className="empty"><Upload/> {t('Your visual library is waiting to grow.')}</p>}</div>:null}{step===9?<Review lang={lang} project={project} pictures={pictures} copy={copy} download={download}/>:null}</>}
function Multi({lang,items,selected,update,type}:{lang:Lang;items:string[];selected:string[];update:(v:string[])=>void;type:string}){const t=(s:string)=>translate(lang,s);return <div className="option-grid compact selectable-list">{items.map(x=><Choice key={x} selected={selected.includes(x)} onClick={()=>update(toggle(selected,x))}><span>{t(x)}</span><small>{t(selected.includes(x)?'Included':type==='section'?'Add section':'Add feature')}</small></Choice>)}</div>}
function DomainCheck({lang,value,status,updateName,updateStatus}:{lang:Lang;value:string;status:DomainStatus;updateName:(v:string)=>void;updateStatus:(v:DomainStatus)=>void}){const t=(s:string)=>translate(lang,s);const normalize=(raw:string)=>{try{return decodeURIComponent(new URL(/^https?:\/\//i.test(raw.trim())?raw.trim():`https://${raw.trim()}`).hostname).toLowerCase().replace(/^www\./,'').replace(/\.$/,'')}catch{return raw.trim().toLowerCase()}};const check=async()=>{const domain=normalize(value);updateName(domain);if(!/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(domain)){updateStatus('invalid');return}updateStatus('checking');try{const response=await fetch(`https://rdap.org/domain/${encodeURIComponent(domain)}`,{headers:{Accept:'application/rdap+json'}});updateStatus(response.ok?'registered':response.status===404?'possibly-available':'error')}catch{updateStatus('error')}};const messages:Record<Exclude<DomainStatus,'idle'>,string>={checking:'Checking registration…',registered:'This domain is already registered.', 'possibly-available':'No registration found — it may be available.',invalid:'Enter a valid domain, for example yourbrand.com.',error:'The check could not be completed. Please try again.'};return <div className="domain-check"><label>{t('Preferred domain name')}<div className="domain-field"><input value={value} onChange={e=>{updateName(e.target.value);updateStatus('idle')}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void check()}}} placeholder="yourbrand.com" inputMode="url" autoCapitalize="none" spellCheck={false}/><button type="button" className="outline" onClick={()=>void check()} disabled={status==='checking'}>{t(status==='checking'?'Checking…':'Check domain')}</button></div></label>{status!=='idle'?<p className={`domain-result ${status}`} role="status">{t(messages[status])}</p>:null}<small>{t('Availability is indicative. Confirm availability and price with a domain registrar.')}</small></div>}
function Review({lang,project,pictures,copy,download}:{lang:Lang;project:Project;pictures:Picture[];copy:()=>void;download:()=>void}){const t=(s:string)=>translate(lang,s);return <div className="review"><div className="review-hero" style={{backgroundImage:pictures[0]?`linear-gradient(90deg,var(--c1),transparent),url(${pictures[0].url})`:undefined}}><small>{project.businessType||t('Business')}</small><h2>{project.headline||project.businessName||t('Your BonsAI is ready.')}</h2><p>{project.subheadline||t('Review the direction and take the specification with you.')}</p><button>{project.cta||'Contact us'}</button></div><div className="review-spec"><Spec empty={t('Not chosen yet')} label={t('Domain')} value={project.domainName}/><Spec empty={t('Not chosen yet')} label={t('Style')} value={project.style}/><Spec empty={t('Not chosen yet')} label={t('Colors')} value={project.palette}/><Spec empty={t('Not chosen yet')} label={t('Typography')} value={project.font}/><Spec empty={t('Not chosen yet')} label={t('Sections')} value={`${project.sections.length}`}/><Spec empty={t('Not chosen yet')} label={t('Features')} value={`${project.features.length}`}/><Spec empty={t('Not chosen yet')} label={t('Pictures')} value={`${pictures.length}`}/></div><div className="review-actions"><button className="primary" onClick={copy}><Copy/> {t('Copy specification')}</button><button className="outline" onClick={download}><Download/> {t('Download')}</button><a className="outline" href="mailto:studio@itbonsai.pl?subject=My%20BonsAI%20website%20concept">{t('Send to BonsAi Studio')}</a></div></div>}
function Spec({label,value,empty='Not chosen yet'}:{label:string;value:string;empty?:string}){return <div><span>{label}</span><b>{value||empty}</b></div>}
function Help({lang}:{lang:Lang}){const t=(s:string)=>translate(lang,s);return <><Brand/><span className="kicker">{t('Workshop help')}</span><h2>{t('We are here while you grow.')}</h2><p>{t('You do not need design terminology. Choose what feels right and BonsAi Studio will translate it into a professional website direction.')}</p><div className="contact-list"><a href="mailto:studio@itbonsai.pl">studio@itbonsai.pl</a><a href="tel:+48501476124">+48 501 476 124</a><a href="https://wa.me/48501476124" target="_blank" rel="noreferrer">WhatsApp</a><span>Gdańsk · Polska</span></div><a className="primary" href="https://itbonsai.pl" target="_blank" rel="noreferrer">{t('Visit itbonsai.pl')} <ChevronRight/></a></>}
function Summary({lang,project,growth,pictures,copy,download,reset}:{lang:Lang;project:Project;growth:number;pictures:Picture[];copy:()=>void;download:()=>void;reset:()=>void}){const t=(s:string)=>translate(lang,s);return <><span className="kicker">{t('Your living specification')}</span><h2>{t('My BonsAI')}</h2><div className="summary-growth"><span>{t('Growth')}</span><b>{Math.round(growth*100)}%</b><i><i style={{width:`${growth*100}%`}}/></i></div><Spec empty={t('Not chosen yet')} label={t('Business')} value={project.businessName}/><Spec empty={t('Not chosen yet')} label={t('Domain')} value={project.domainName}/><Spec empty={t('Not chosen yet')} label={t('Style')} value={project.style}/><Spec empty={t('Not chosen yet')} label="Palette" value={project.palette}/><Spec empty={t('Not chosen yet')} label={t('Typography')} value={project.font}/><Spec empty={t('Not chosen yet')} label={t('Structure')} value={`${project.sections.length}`}/><Spec empty={t('Not chosen yet')} label={t('Functions')} value={`${project.features.length}`}/><Spec empty={t('Not chosen yet')} label={t('Pictures')} value={`${pictures.length}`}/><div className="drawer-actions"><button className="primary" onClick={copy}><Copy/> {t('Copy specification')}</button><button className="outline" onClick={download}><Download/> {t('Download')}</button><button className="text-danger" onClick={reset}><RotateCcw/> {t('Start again')}</button></div></>}
