import {useState} from 'react';
import {Activity,ArrowRight,Bell,Bot,BriefcaseBusiness,Building2,CalendarDays,CheckCircle2,ChevronRight,Circle,FileText,Goal,LayoutDashboard,Leaf,Menu,Mountain,Plus,Search,Settings,Users,X,Zap} from 'lucide-react';
type Page='today'|'city'|'mountain'|'office'|'garden';
type Task={id:number;name:string;meta:string;done:boolean};
const pages=[['today','Dzisiaj','Spokojny przegląd dnia',LayoutDashboard],['city','City','Ludzie i współpraca',Building2],['mountain','Mountain','Cele i postęp',Mountain],['office','Office','Codzienna praca',BriefcaseBusiness],['garden','Garden','Aplikacje i automatyzacje',Leaf]] as const;
const goals=[['Rozwój produktu BonsAI OS',68],['Zadowolenie klientów 90%',74],['Optymalizacja procesów',42]] as const;
const people=[['MK','Marta Kowalska','Design Lead'],['PZ','Piotr Zieliński','Tech Lead'],['KL','Kasia Lewandowska','Project Manager'],['TW','Tomasz Wiśniewski','Developer']];
function Head({icon:I,title,action}:{icon:any;title:string;action?:string}){return <div className="head"><h2><I/>{title}</h2>{action&&<button>{action}<ArrowRight/></button>}</div>}
function Tasks({tasks,toggle}:{tasks:Task[];toggle:(n:number)=>void}){return <div className="tasks">{tasks.map(t=><button className={t.done?'done':''} onClick={()=>toggle(t.id)} key={t.id}>{t.done?<CheckCircle2/>:<Circle/>}<span><b>{t.name}</b><small>{t.meta}</small></span><ChevronRight/></button>)}</div>}
function Team(){return <>{people.map((p,i)=><div className="person" key={p[1]}><span>{p[0]}</span><p><b>{p[1]}</b><small>{p[2]}</small></p><em>{i===1?'W trakcie':'Skupiona/y'}</em></div>)}</>}
function Side({page,setPage,open,setOpen}:{page:Page;setPage:(p:Page)=>void;open:boolean;setOpen:(v:boolean)=>void}){return <aside className={open?'open':''}><div className="logo"><span><Leaf/></span>BonsAI <i>OS</i></div><button className="close" onClick={()=>setOpen(false)}><X/></button><nav>{pages.map(([id,label,desc,I])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}} key={id}><I/><span><b>{label}</b><small>{desc}</small></span><ChevronRight/></button>)}</nav><div className="tools"><button><Search/>Szukaj</button><button><Settings/>Ustawienia</button></div><div className="profile"><span>AN</span><p><b>Anna Nowak</b><small>Product Lead</small></p></div></aside>}
function Today({tasks,toggle,setPage}:{tasks:Task[];toggle:(n:number)=>void;setPage:(p:Page)=>void}){return <div className="page"><div className="welcome"><p>Poniedziałek, 24 sierpnia</p><h1>Dzień dobry, Anna.</h1><span>Jedno skupienie. Cztery kolejne kroki. Spokojny dzień pracy.</span></div><div className="daily"><section className="focus"><Head icon={Goal} title="Skupienie na dziś"/><h2>Przygotuj plan wdrożenia dla projektu Aurora</h2><div className="meta"><span>Aurora</span><span><Users/>3 osoby</span><span><CalendarDays/>28 sierpnia</span></div><button className="primary" onClick={()=>setPage('city')}>Otwórz projekt <ArrowRight/></button><div className="branch">枝</div></section><section><Head icon={ArrowRight} title="Następny krok" action={`${tasks.filter(t=>t.done).length}/${tasks.length}`}/><Tasks tasks={tasks} toggle={toggle}/><button className="link" onClick={()=>setPage('office')}>Pełen plan dnia <ArrowRight/></button></section><section className="attention"><Head icon={Bell} title="Uwaga"/>{['Umowa wymaga decyzji','Wspomniano Cię w Aurora','3 dokumenty do akceptacji'].map(x=><button key={x}><FileText/><span><b>{x}</b><small>Wymaga Twojej uwagi</small></span><ChevronRight/></button>)}</section></div><div className="overview"><section><Head icon={Users} title="Puls zespołu" action="City"/><Team/></section><section><Head icon={Goal} title="Postępy celów" action="Mountain"/>{goals.map(g=><div className="goal" key={g[0]}><p><b>{g[0]}</b><small>Q3 · aktywny cel</small></p><i><i style={{width:`${g[1]}%`}}/></i><strong>{g[1]}%</strong></div>)}</section><section><Head icon={Bot} title="Kodama działa w tle"/>{['Uporządkował 12 dokumentów','Wysłał podsumowanie spotkania','Zaktualizował 3 zadania'].map(x=><div className="activity" key={x}><Zap/><span>{x}</span></div>)}</section></div></div>}
function Module({icon:I,label,title,copy,children}:{icon:any;label:string;title:string;copy:string;children:any}){return <div className="page module"><header><span><I/></span><div><p>{label}</p><h1>{title}</h1><small>{copy}</small></div><button className="primary"><Plus/> Utwórz nowe</button></header>{children}</div>}
function City(){return <Module icon={Building2} label="BonsAI City" title="Wspólna przestrzeń zespołu." copy="Projekty, ludzie i wiedza — razem, bez szukania po różnych narzędziach."><div className="two"><section><Head icon={BriefcaseBusiness} title="Aktywne projekty" action="Wszystkie"/>{[['Aurora',67],['Borealis',78],['Cedr',31]].map(p=><div className="project" key={p[0] as string}><span>{(p[0] as string)[0]}</span><p><b>Projekt {p[0]}</b><small>Najważniejsze informacje w jednym miejscu</small><i><i style={{width:`${p[1]}%`}}/></i></p><strong>{p[1]}%</strong></div>)}</section><section><Head icon={Users} title="Zespół dzisiaj" action="8 osób"/><Team/></section></div></Module>}
function MountainPage(){const [pick,setPick]=useState(0);return <Module icon={Mountain} label="BonsAI Mountain" title="Każdy cel ma następny krok." copy="Duże ambicje podzielone na widoczne etapy i działania na dziś."><div className="mount"><section><Head icon={Goal} title="Twoje cele"/>{goals.map((g,i)=><button className={pick===i?'selected':''} onClick={()=>setPick(i)} key={g[0]}><span><b>{g[0]}</b><small>Q3 · etap 3 z 5</small></span><strong>{g[1]}%</strong><i><i style={{width:`${g[1]}%`}}/></i></button>)}</section><section className="summit"><small>WYBRANY SZCZYT</small><h2>{goals[pick][0]}</h2><div className="path">✓ — ✓ — ③ — ④ — ⑤</div><h3>Uruchom wersję pilotażową</h3><p>Przygotuj środowisko, zbierz grupę testową i ustal kryteria sukcesu.</p><button className="primary">Otwórz następny krok <ArrowRight/></button></section></div></Module>}
function Office({tasks,toggle}:{tasks:Task[];toggle:(n:number)=>void}){const [note,setNote]=useState('');return <Module icon={BriefcaseBusiness} label="BonsAI Office" title="Twój dzień, bez zbędnych ekranów." copy="Zadania, kalendarz i notatki w jednej spokojnej przestrzeni."><div className="three"><section><Head icon={CheckCircle2} title="Plan dnia"/><Tasks tasks={tasks} toggle={toggle}/></section><section className="agenda"><Head icon={CalendarDays} title="Kalendarz"/>{[['09:00','Daily Aurora'],['12:30','Feedback do makiet'],['14:00','Spotkanie zespołu']].map(x=><div key={x[0]}><time>{x[0]}</time><p><b>{x[1]}</b><small>25 min · spotkanie</small></p></div>)}</section><section className="notes"><Head icon={FileText} title="Szybka notatka"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Zapisz myśl, zanim ucieknie…"/><button disabled={!note} onClick={()=>setNote('')} className="primary">Zapisz notatkę</button></section></div></Module>}
function Garden(){const [apps,setApps]=useState([true,true,true,false]);return <Module icon={Leaf} label="BonsAI Garden" title="Twoje aplikacje. Jedna spokojna warstwa." copy="Garden pokazuje tylko to, co wymaga uwagi. Kodama zajmuje się resztą."><div className="three"><section><Head icon={Activity} title="Połączone aplikacje"/>{['Gmail','Kalendarz','Google Drive','Slack'].map((a,i)=><div className="integration" key={a}><span>{a[0]}</span><p><b>{a}</b><small>Informacje i działania</small></p><button className={apps[i]?'switch on':'switch'} onClick={()=>setApps(v=>v.map((x,j)=>j===i?!x:x))}><i/></button></div>)}</section><section className="attention"><Head icon={Bell} title="Inbox uwagi"/>{['Umowa wymaga decyzji','Wspomniano Cię w Aurora','3 dokumenty do akceptacji'].map(x=><button key={x}><FileText/><span><b>{x}</b><small>Wymaga uwagi</small></span><ChevronRight/></button>)}</section><section><Head icon={Bot} title="Kodama"/>{['Porządkuj nowe dokumenty','Podsumuj spotkania','Pilnuj zadań bez postępu'].map(x=><div className="rule" key={x}><CheckCircle2/><span><b>{x}</b><small>Aktywna reguła</small></span></div>)}</section></div></Module>}
export function AppOS(){const [page,setPage]=useState<Page>('today'),[menu,setMenu]=useState(false),[toast,setToast]=useState(false),[tasks,setTasks]=useState<Task[]>([{id:1,name:'Zatwierdź zakres projektu',meta:'Aurora · oczekuje na Ciebie',done:false},{id:2,name:'Przegląd dokumentu BRD',meta:'Aurora · do 11:00',done:false},{id:3,name:'Feedback do makiet',meta:'Strona www · do 12:30',done:false},{id:4,name:'Spotkanie zespołu',meta:'Aurora · 14:00',done:false}]);const toggle=(id:number)=>{setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t));setToast(true);setTimeout(()=>setToast(false),1400)};return <div className="shell"><Side page={page} setPage={setPage} open={menu} setOpen={setMenu}/><div className="workspace"><header className="top"><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><button className="search"><Search/>Wyszukaj w BonsAI OS <kbd>⌘ K</kbd></button><button><Bell/></button><button><CalendarDays/></button><span>AN</span></header><main>{page==='today'?<Today tasks={tasks} toggle={toggle} setPage={setPage}/>:page==='city'?<City/>:page==='mountain'?<MountainPage/>:page==='office'?<Office tasks={tasks} toggle={toggle}/>:<Garden/>}</main></div>{toast&&<div className="toast"><CheckCircle2/>Plan dnia zaktualizowany</div>}</div>}
